#! /bin/bash
#
# clone all needed addons
#
# 2012 Dan Wilcox danomatika.com
#
# references:
# 	http://www.cyberciti.biz/faq/bash-for-loop-array/
#	http://tldp.org/LDP/abs/html/complexfunct.html
#   http://stackoverflow.com/questions/1063347/passing-arrays-as-parameters-in-bash
#

### variables

WD=$(dirname $0)
ADDONS_DIR="../../../addons"

# addons
danomatika_addons=( 
	"ofxPd"
	"ofxAppUtils"
)

### functions

# clone a list of addons form Github
# $1 - Github user name
# $2 - array of addon repo names
function cloneAddons {
	local user=$1
	local array=("$@")
	
	# load array from argument
	for (( i = 1 ; i < ${#array[@]} ; i++ )) ; do
		printf "${format}" $i "${array[$i]}"
	done

    # clone
	for i in "${array[@]}" ; do
		git clone git://github.com/$user/$i.git
	done
	return
}

### do stuff

cd $WD
cd $ADDONS_DIR

# clone those addons

cloneAddons danomatika "${danomatika_addons[@]}"